export const organDescriptions = {
    heart: "The heart is a muscular organ that pumps blood throughout the body.",
    brain: "The brain is the central organ of the human nervous system.",
    eye: "The eye is the organ that allows vision.",
    kidney: "The kidneys filter waste from the blood and regulate fluids.",
    liver: "The liver detoxifies chemicals and metabolizes drugs.",
    pancreas: "The pancreas produces enzymes that help digestion.",
    sm_intestine: "The small intestine absorbs nutrients from food.",
    lung: "The lungs are responsible for breathing and gas exchange.",
    skin: "The skin protects the body and regulates temperature.",
    lg_intestine: "The large intestine absorbs water and forms stool.",
    prostate: "The prostate helps produce semen.",
    pelvis: "The pelvis supports the spinal column and legs.",
    legs: "The legs allow movement and support body weight.",
    blood_vasculature: "The blood vasculature transports blood throughout the body.",
    urinary_bladder: "The bladder stores urine before excretion.",
    ureter: "The ureters carry urine from the kidneys to the bladder.",
    larynx: "The larynx is involved in breathing, sound production, and protecting the trachea.",
    lymph_node: "Lymph nodes filter lymph and are part of the immune system.",
    bronchus: "The bronchi carry air from the trachea into the lungs.",
    palatine_tonsil: "The palatine tonsils are part of the immune system.",
    spinal_cord: "The spinal cord transmits signals between the brain and the body.",
    spleen: "The spleen filters blood and supports the immune system.",
    thymus: "The thymus is involved in the development of the immune system.",
    trachea: "The trachea provides a clear airway to the lungs.",
    vertebrae: "The vertebrae are bones that form the spine.",
    rectus_femoris: "The rectus femoris is a muscle of the thigh.",
    cricoarytenoid: "The cricoarytenoid is a muscle involved in vocal cord movement.",
    cystic_duct: "The cystic duct connects the gallbladder to the bile ducts.",
    gallbladder: "The gallbladder stores bile produced by the liver.",
    urethra: "The urethra carries urine out of the body.",
    hyoid: "The hyoid is a bone in the neck that supports the tongue."
};


